# Generated by Django 3.1.5 on 2021-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='yo', max_length=30),
            preserve_default=False,
        ),
    ]
